"""ChromaDB connection manager and storage operations."""

import asyncio
import chromadb  # type: ignore
from chromadb.utils import embedding_functions  # type: ignore
from config import settings
from app.logger import logger


class ChromaDBClient:
    """ChromaDB connection manager with lazy initialization.
    
    Handles connection to the shared ChromaDB instance at ../data/chroma_db.
    ChromaDB's OllamaEmbeddingFunction automatically generates embeddings 
    during upsert operations, so we don't need separate embedding generation.
    """
    
    def __init__(self):
        self._client: chromadb.PersistentClient | None = None
        self._collection = None
        self._lock = asyncio.Lock()
    
    async def connect(self) -> None:
        """Initialize ChromaDB connection to shared data directory."""
        async with self._lock:
            if self._client is None:
                try:
                    self._client = chromadb.PersistentClient(path=str(settings.CHROMA_PATH))
                    logger.info(f"ChromaDB connected to {settings.CHROMA_PATH}")
                except Exception as e:
                    logger.error(f"Failed to connect to ChromaDB: {e}")
                    raise
    
    async def get_collection(self):
        """Get or create ChromaDB collection with Ollama embeddings.
        
        Returns:
            ChromaDB collection (embeddings generated by ChromaDB's OllamaEmbeddingFunction)
        """
        if self._client is None:
            await self.connect()
        
        if self._collection is None:
            try:
                # ChromaDB's OllamaEmbeddingFunction calls Ollama for embeddings during upsert
                embedding_func = embedding_functions.OllamaEmbeddingFunction(
                    url=f"{settings.OLLAMA_HOST}/api/embeddings",
                    model_name=settings.EMB_MODEL,
                )
                
                self._collection = self._client.get_or_create_collection(
                    settings.CHROMA_COLLECTION_NAME,
                    metadata={"hnsw:space": settings.CHROMA_DISTANCE},
                    embedding_function=embedding_func,
                )
                
                logger.info(
                    f"Collection '{settings.CHROMA_COLLECTION_NAME}' ready "
                    f"(model: {settings.EMB_MODEL}, distance: {settings.CHROMA_DISTANCE})"
                )
            except Exception as e:
                logger.error(f"Failed to get or create collection: {e}")
                raise
        
        return self._collection
    
    async def delete_collection(self, rebuild: bool = False) -> None:
        """Delete collection for rebuild mode.
        
        Args:
            rebuild: If True, delete the collection
        """
        if not rebuild or not self._client:
            return
        
        try:
            self._client.delete_collection(settings.CHROMA_COLLECTION_NAME)
            self._collection = None
            logger.info(f"Deleted collection '{settings.CHROMA_COLLECTION_NAME}' (rebuild mode)")
        except Exception as e:
            logger.warning(f"Failed to delete collection: {e}")
    
    async def check_existing_ids(self, ids: list[str]) -> set[str]:
        """Check which document IDs already exist in collection.
        
        Used for deduplication to avoid re-processing documents.
        
        Args:
            ids: List of document IDs to check
            
        Returns:
            Set of IDs that already exist in collection
        """
        if not ids:
            return set()
        
        try:
            collection = await self.get_collection()
            result = collection.get(ids=ids, include=[])
            return set(result.get("ids", []))
        except Exception as e:
            logger.error(f"Failed to check existing IDs: {e}")
            return set()
    
    async def upsert_batch(
        self,
        ids: list[str],
        documents: list[str],
        metadatas: list[dict],
    ) -> None:
        """Store documents in ChromaDB.
        
        ChromaDB automatically generates embeddings via OllamaEmbeddingFunction.
        
        Args:
            ids: Document IDs (stable, based on content hash)
            documents: Raw document texts (will be embedded by ChromaDB)
            metadatas: Document metadata (file source, chunk index, etc.)
        """
        if not ids:
            return
        
        try:
            collection = await self.get_collection()
            collection.upsert(ids=ids, documents=documents, metadatas=metadatas)
            logger.debug(f"Upserted {len(ids)} documents to ChromaDB")
        except Exception as e:
            logger.error(f"Failed to upsert batch: {e}")
            raise


# Global ChromaDB client instance
chroma_client = ChromaDBClient()
